mysql:
  dbHost: my-instance.cvefazkbfyp3.us-east-1.rds.amazonaws.com
  dbSchema: beststories
  dbUsername: root
  dbPassword: thepassword

KafkaServer: kafka
ESAddr: http://localhost:9200


image:
  repository: bh7cw/processor-webapp
  name: processor-webapp

imagePullSecrets: docker-hub
port: 8080

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 45
  periodSeconds: 5

livenessProbe:
  path: /v1/helloworld
  initialDelaySeconds: 60
  periodSeconds: 5

deployment:
  replicas: 3
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
  svc:
    port: 80