mysql:
  dbHost: rdsbest.cvefazkbfyp3.us-east-1.rds.amazonaws.com
  dbSchema: beststories
  dbUsername: root
  dbPassword: MysqlPwd123

kafkaServer: kafka.default.svc.cluster.local:9092
esAddr: http://elasticsearch-master:9200

image:
  repository: bh7cw/processor-webapp
  name: processor-webapp

imagePullSecrets: docker-hub
port: 8080

readinessProbe:
  path: /story
  initialDelaySeconds: 45
  periodSeconds: 5

livenessProbe:
  path: /hello
  initialDelaySeconds: 60
  periodSeconds: 5

deployment:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
  # Monitoring: Adjust Prometheus configuration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  svc:
    port: 80