apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  DBUserName: {{ .Values.mysql.dbUsername | b64enc | quote }}
  DBPassword: {{ .Values.mysql.dbPassword | b64enc | quote }}